### ISSUE TITLE
Shopify redirectUri error

### ISSUE THREAD

**Issue by joshbedo** [jhillhouse92/shopify-app-node-starter#1]
I'm trying to set this project up and I'm stuck on this error. I was wondering if you've seen it before or know how I can go about fixing it. Thanks!

![](http://i.imgur.com/onybj9S.jpg)

**Comment by jhillhouse92** [comment]
This has to do with exchanging the temporary token for a permanent token. If you check out the node Shopify module at https://www.npmjs.com/package/shopify-node-api you will see where that error is coming from. It could perhaps mean that the secret, API key, or redirect uri is incorrect. I'm on vacation currently, but when I get back in a week I will do investigation to see if it's related with the Node Shopify startup implementation of the Node Shopify module. Thanks for reporting the issue and using this library!

Regards,
Joe

**Comment by joshbedo** [comment]
Alright I'll try creating a new app and see if I can resolve this, I'm positive the params i have now are correct. Thanks!

**Comment by jhillhouse92** [comment]
Can you show a screenshot of your app settings like this?

![image](https://cloud.githubusercontent.com/assets/8386883/16156259/68777da0-3481-11e6-883a-10d388f7203c.png)

**Comment by jhillhouse92** [comment]
Also, are you installing this from the Shopify App store? You can't just go to /oauth. You have to click Edit App Store Listing. Then, on the preview page, click "View App Listing". Finally, click "Get" on the app page.
1. ![image](https://cloud.githubusercontent.com/assets/8386883/16156432/3b074872-3482-11e6-8129-a6feed0a0557.png)
2. ![image](https://cloud.githubusercontent.com/assets/8386883/16156458/5c1cea12-3482-11e6-88e6-a402e572029f.png)
3. ![image](https://cloud.githubusercontent.com/assets/8386883/16156484/7b47e9be-3482-11e6-90ff-5f4c66a81f45.png)

You will be prompted to login with Shopify which then will prompt you to approve the permissions for the app and upon approval will redirect to the redirect_url (/oauth). At this point, the request will be from Shopify and it should be authentic.

Let me know if this doesn't work for you.

**Comment by jhillhouse92** [comment]
@joshbedo Were you able to resolve this issue?

**Comment by joshbedo** [comment]
Sorry i've been really busy lately, I'll give this a shot tonight and send over screenshots. Thanks!
